export const SCHOOL_LINKS = {
  "CII Liceum Ogólnokształcące z Oddziałami Integracyjnymi im. Księdza Józefa Woźniaka": "https://waszaedukacja.pl/ponadgimnazjalne/cii-liceum-z-oddzialami-integracyjnymi-im-ks-j-wozniaka-warszawa-126",
  "CLIX Liceum Ogólnokształcące im. Króla Jana III Sobieskiego": "https://waszaedukacja.pl/ponadgimnazjalne/clix-liceum-im-krola-jana-iii-sobieskiego-warszawa-18805",
  "CLV Liceum Ogólnokształcące z Oddziałami Dwujęzycznymi im. Bohaterek Powstania Warszawskiego": "https://waszaedukacja.pl/ponadgimnazjalne/clv-liceum-z-oddzialami-dwujezycznymi-im-bohaterek-powstania-warszawskiego-warszawa-18810",
  "CLVI Liceum Ogólnokształcące Integracyjne „Przy Łazienkach Królewskich”": "https://waszaedukacja.pl/ponadgimnazjalne/clvi-liceum-integracyjne-przy-lazienkach-krolewskich-warszawa-18811",
  "CLVII Liceum Ogólnokształcące im. Marii Skłodowskiej-Curie": "https://waszaedukacja.pl/ponadgimnazjalne/clvii-liceum-im-marii-sklodowskiej-curie-warszawa-18812",
  "CLVIII Liceum Ogólnokształcące z Oddziałami Dwujęzycznymi im. Księżnej Izabeli Czartoryskiej": "https://waszaedukacja.pl/ponadgimnazjalne/clviii-liceum-im-ksieznej-izabeli-czartoryskiej-warszawa-18804",
  "CLX Liceum Ogólnokształcące im. gen. dyw. Stefana Roweckiego „Grota”": "https://waszaedukacja.pl/ponadgimnazjalne/clx-liceum-im-gen-dyw-stefana-roweckiego-grota-warszawa-18806",
  "CLXI Liceum Ogólnokształcące im. Władysława Bartoszewskiego": "https://waszaedukacja.pl/ponadgimnazjalne/clxi-liceum-im-wladyslawa-bartoszewskiego-warszawa-18809",
  "CLXII Liceum Ogólnokształcące im. Szarych Szeregów": "https://waszaedukacja.pl/ponadgimnazjalne/clxii-liceum-warszawa-18813",
  "CLXIII Liceum Ogólnokształcące im. Czesława Niemena w Warszawie": "https://waszaedukacja.pl/ponadgimnazjalne/clxiii-liceum-im-czeslawa-niemena-warszawa-18807",
  "CLXIV Liceum Ogólnokształcące Mistrzostwa Sportowego": "https://waszaedukacja.pl/ponadgimnazjalne/clxiv-liceum-mistrzostwa-sportowego-warszawa-18808",
  "CLXV Liceum Ogólnokształcące": "https://waszaedukacja.pl/ponadgimnazjalne/clxv-liceum-warszawa-20110",
  "CLXVI Liceum Ogólnokształcące z Oddziałami Sportowymi": "https://waszaedukacja.pl/ponadgimnazjalne/clxvi%20liceum%20z%20oddzialami%20sportowymi-warszawa-67832",
  "CV Liceum Ogólnokształcące im. Zbigniewa Herberta": "https://waszaedukacja.pl/ponadgimnazjalne/cv-liceum-im-zbigniewa-herberta-warszawa-294",
  "CX Liceum Ogólnokształcące im. Roberta Schumana": "https://waszaedukacja.pl/ponadgimnazjalne/cx-liceum-im-roberta-schumana-warszawa-296",
  "CXI Liceum Ogólnokształcące z Oddziałami Integracyjnymi im. Stefana Kisielewskiego": "https://waszaedukacja.pl/ponadgimnazjalne/cxi-liceum-z-oddzialami-integracyjnymi-im-stefana-kisielewskiego-warszawa-297",
  "CXIV Liceum Ogólnokształcące im. Jana Kilińskiego": "https://waszaedukacja.pl/ponadgimnazjalne/cxiv-liceum-im-jana-kilinskiego-warszawa-298",
  "CXIX Liceum Ogólnokształcące im. Jacka Kuronia": "https://waszaedukacja.pl/ponadgimnazjalne/cxix-liceum-im-jacka-kuronia-warszawa-299",
  "CXXII Liceum Ogólnokształcące im. Ignacego Domeyki": "https://waszaedukacja.pl/ponadgimnazjalne/cxxii-liceum-im-ignacego-domeyki-warszawa-306",
  "CXXV Liceum Ogólnokształcące im. Waldemara Milewicza": "https://waszaedukacja.pl/ponadgimnazjalne/cxxv-liceum-im-waldemara-milewicza-warszawa-307",
  "CXXXVII Liceum Ogólnokształcące z Oddziałami Dwujęzycznymi im. Roberta Schumana": "https://waszaedukacja.pl/ponadgimnazjalne/cxxxvii-liceum-z-oddzialami-dwujezycznymi-im-roberta-schumana-warszawa-308",
  "I Liceum Ogólnokształcące z Oddziałami Integracyjnymi im. Bolesława Limanowskiego": "https://waszaedukacja.pl/ponadgimnazjalne/i-liceum-z-oddzialami-integracyjnymi-im-boleslawa-limanowskiego-warszawa-309",
  "II Liceum Ogólnokształcące z Oddziałami Dwujęzycznymi im. Stefana Batorego": "https://waszaedukacja.pl/ponadgimnazjalne/ii-liceum-z-oddzialami-dwujezycznymi-im-stefana-batorego-warszawa-310",
  "III Liceum Ogólnokształcące im. gen. Józefa Sowińskiego": "https://waszaedukacja.pl/ponadgimnazjalne/iii-liceum-im-gen-jozefa-sowinskiego-warszawa-311",
  "IV Liceum Ogólnokształcące im. Adama Mickiewicza": "https://waszaedukacja.pl/ponadgimnazjalne/iv-liceum-im-adama-mickiewicza-warszawa-312",
  "IX Liceum Ogólnokształcące im. Klementyny Hoffmanowej": "https://waszaedukacja.pl/ponadgimnazjalne/ix-liceum-im-klementyny-hoffmanowej-warszawa-313",
  "L Liceum Ogólnokształcące z Oddziałami Integracyjnymi im. Ruy Barbosy": "https://waszaedukacja.pl/ponadgimnazjalne/l-liceum-z-oddzialami-integracyjnymi-im-ruy-barbosy-warszawa-314",
  "LI Liceum Ogólnokształcące im. Tadeusza Kościuszki": "https://waszaedukacja.pl/ponadgimnazjalne/li-liceum-im-tadeusza-kosciuszki-warszawa-315",
  "LII Liceum Ogólnokształcące im. Władysława Stanisława Reymonta": "https://waszaedukacja.pl/ponadgimnazjalne/lii-liceum-im-wladyslawa-stanislawa-reymonta-warszawa-316",
  "LIX Liceum Ogólnokształcące Mistrzostwa Sportowego im. Janusza Kusocińskiego": "https://waszaedukacja.pl/ponadgimnazjalne/lix-liceum-mistrzostwa-sportowego-im-janusza-kusocinskiego-warszawa-317",
  "LVI Liceum Ogólnokształcące im. Rotmistrza Witolda Pileckiego": "https://waszaedukacja.pl/ponadgimnazjalne/lvi-liceum-im-leona-kruczkowskiego-warszawa-318",
  "LVIII Liceum Ogólnokształcące im. Krzysztofa Kamila Baczyńskiego": "https://waszaedukacja.pl/ponadgimnazjalne/lviii-liceum-im-krzysztofa-kamila-baczynskiego-warszawa-319",
  "LX Liceum Ogólnokształcące im. Wojciecha Górskiego": "https://waszaedukacja.pl/ponadgimnazjalne/lx-liceum-im-wojciecha-gorskiego-warszawa-320",
  "LXII Liceum Ogólnokształcące Mistrzostwa Sportowego im. Generała Broni Władysława Andersa": "https://waszaedukacja.pl/ponadgimnazjalne/lxii-liceum-mistrzostwa-sportowego-im-gen-broni-wladyslawa-andersa-warszawa-322",
  "LXIII Liceum Ogólnokształcące im. Lajosa Kossutha": "https://waszaedukacja.pl/ponadgimnazjalne/lxiii-liceum-im-lajosa-kossutha-warszawa-323",
  "LXIV Liceum Ogólnokształcące im. Stanisława Ignacego Witkiewicza \"Witkacego\"": "https://waszaedukacja.pl/ponadgimnazjalne/lxiv-liceum-im-stanislawa-ignacego-witkiewicza-warszawa-324",
  "LXIX Liceum Ogólnokształcące z Oddziałami Integracyjnymi im. Bohaterów Powstania Warszawskiego 1944": "https://waszaedukacja.pl/ponadgimnazjalne/lxix-liceum-z-oddzialami-integracyjnymi-im-bohaterow-powstania-warszawskiego-1944-warszawa-326",
  "LXV Liceum Ogólnokształcące z Oddziałami Integracyjnymi im. gen. Józefa Bema": "https://waszaedukacja.pl/ponadgimnazjalne/lxv-liceum-z-oddzialami-integracyjnymi-im-gen-jozefa-bema-warszawa-327",
  "LXVII Liceum Ogólnokształcące im. Jana Nowaka-Jeziorańskiego": "https://waszaedukacja.pl/ponadgimnazjalne/lxvii-liceum-im-jana-nowaka-jezioranskiego-warszawa-328",
  "LXVIII Liceum Ogólnokształcące im. Tytusa Chałubińskiego": "https://waszaedukacja.pl/ponadgimnazjalne/lxviii-liceum-im-tytusa-chalubinskiego-warszawa-329",
  "LXX Liceum Ogólnokształcące im. Aleksandra Kamińskiego": "https://waszaedukacja.pl/ponadgimnazjalne/lxx-liceum-im-aleksandra-kaminskiego-warszawa-330",
  "LXXII Liceum Ogólnokształcące im. gen. Jakuba Jasińskiego": "https://waszaedukacja.pl/ponadgimnazjalne/lxxii-liceum-im-gen-jakuba-jasinskiego-warszawa-332",
  "LXXV Liceum Ogólnokształcące im. Jana III Sobieskiego": "https://waszaedukacja.pl/ponadgimnazjalne/lxxv-liceum-im-jana-iii-sobieskiego-warszawa-336",
  "LXXVI Liceum Ogólnokształcące im. Marszałka Józefa Piłsudskiego": "https://waszaedukacja.pl/ponadgimnazjalne/lxxvi-liceum-im-marsz-jozefa-pilsudskiego-warszawa-335",
  "LXXVIII Liceum Ogólnokształcące im. Marii Pawlikowskiej-Jasnorzewskiej": "https://waszaedukacja.pl/ponadgimnazjalne/lxxviii-liceum-im-marii-jasnorzewskiej-pawlikowskiej-warszawa-337",
  "LXXX Liceum Ogólnokształcące im. Leopolda Staffa": "https://waszaedukacja.pl/ponadgimnazjalne/lxxx-liceum-im-leopolda-staffa-warszawa-338",
  "LXXXI Liceum Ogólnokształcące im. Aleksandra Fredry": "https://waszaedukacja.pl/ponadgimnazjalne/lxxxi-liceum-im-aleksandra-fredry-warszawa-339",
  "LXXXIII Liceum Ogólnokształcące im. Emiliana Konopczyńskiego": "https://waszaedukacja.pl/ponadgimnazjalne/lxxxiii-liceum-im-emiliana-konopczynskiego-warszawa-340",
  "LXXXIV Liceum Ogólnokształcące im. Bohaterów Narwiku": "https://waszaedukacja.pl/ponadgimnazjalne/lxxxiv-liceum-im-bohaterow-narwiku-warszawa-341",
  "LXXXVI Liceum Ogólnokształcące im. Batalionu \"Zośka\"": "https://waszaedukacja.pl/ponadgimnazjalne/lxxxvi-liceum-im-batalionu-zoska-warszawa-342",
  "LXXXVII Liceum Ogólnokształcące im. gen. Leopolda Okulickiego": "https://waszaedukacja.pl/ponadgimnazjalne/lxxxvii-liceum-im-gen-leopolda-okulickiego-warszawa-343",
  "LXXXVIII Liceum Ogólnokształcące im. Michała Konarskiego": "https://waszaedukacja.pl/ponadgimnazjalne/lxxxviii-liceum-im-michala-konarskiego-warszawa-344",
  "V Liceum Ogólnokształcące im. Księcia Józefa Poniatowskiego": "https://waszaedukacja.pl/ponadgimnazjalne/v-liceum-im-ks-jozefa-poniatowskiego-warszawa-325",
  "VI Liceum Ogólnokształcące im. Tadeusza Reytana": "https://waszaedukacja.pl/ponadgimnazjalne/vi-liceum-im-tadeusza-reytana-warszawa-291",
  "VII Liceum Ogólnokształcące im. Juliusza Słowackiego": "https://waszaedukacja.pl/ponadgimnazjalne/vii-liceum-im-juliusza-slowackiego-warszawa-290",
  "VIII Liceum Ogólnokształcące im. Władysława IV": "https://waszaedukacja.pl/ponadgimnazjalne/viii-liceum-im-wladyslawa-iv-warszawa-289",
  "X Liceum Ogólnokształcące im. Królowej Jadwigi": "https://waszaedukacja.pl/ponadgimnazjalne/x-liceum-im-krolowej-jadwigi-warszawa-288",
  "XCII Liceum Ogólnokształcące z Oddziałami Integracyjnymi": "https://waszaedukacja.pl/ponadgimnazjalne/xcii-liceum-z-oddzialami-integracyjnymi-warszawa-287",
  "XCIV Liceum Ogólnokształcące im. gen. Stanisława Maczka": "https://waszaedukacja.pl/ponadgimnazjalne/xciv-liceum-im-gen-stanislawa-maczka-warszawa-222",
  "XCIX Liceum Ogólnokształcące z Oddziałami Dwujęzycznymi im. Zbigniewa Herberta": "https://waszaedukacja.pl/ponadgimnazjalne/xcix-liceum-z-oddzialami-dwujezycznymi-im-zbigniewa-herberta-warszawa-221",
  "XCVI Liceum Ogólnokształcące im. Agnieszki Osieckiej": "https://waszaedukacja.pl/ponadgimnazjalne/xcvi-liceum-im-a-osieckiej-warszawa-220",
  "XCVII Liceum Ogólnokształcące im. Olimpijczyków Polskich": "https://waszaedukacja.pl/ponadgimnazjalne/xcvii-liceum-im-olimpijczykow-polskich-warszawa-219",
  "XI Liceum Ogólnokształcące im. Mikołaja Reja": "https://waszaedukacja.pl/ponadgimnazjalne/xi-liceum-im-mikolaja-reja-warszawa-218",
  "XII Liceum Ogólnokształcące im. Henryka Sienkiewicza": "https://waszaedukacja.pl/ponadgimnazjalne/xii-liceum-im-henryka-sienkiewicza-warszawa-217",
  "XIII Liceum Ogólnokształcące z Oddziałami Dwujęzycznymi im. płk. Leopolda Lisa-Kuli": "https://waszaedukacja.pl/ponadgimnazjalne/xiii-liceum-z-oddzialami-dwujezycznymi-im-plk-leopolda-lisa-kuli-warszawa-215",
  "XIV Liceum Ogólnokształcące im. Stanisława Staszica": "https://waszaedukacja.pl/ponadgimnazjalne/xiv-liceum-im-stanislawa-staszica-warszawa-213",
  "XIX Liceum Ogólnokształcące im. Powstańców Warszawy": "https://waszaedukacja.pl/ponadgimnazjalne/xix-liceum-im-powstancow-warszawy-warszawa-211",
  "XL Liceum Ogólnokształcące z Oddziałami Dwujęzycznymi im. Stefana Żeromskiego": "https://waszaedukacja.pl/ponadgimnazjalne/xl-liceum-z-oddzialami-dwujezycznymi-im-stefana-zeromskiego-warszawa-210",
  "XLI Liceum Ogólnokształcące im. Joachima Lelewela": "https://waszaedukacja.pl/ponadgimnazjalne/xli-liceum-im-joachima-lelewela-warszawa-209",
  "XLII Liceum Ogólnokształcące im. Marii Konopnickiej": "https://waszaedukacja.pl/ponadgimnazjalne/xlii-liceum-im-marii-konopnickiej-warszawa-208",
  "XLIII Liceum Ogólnokształcące im. Kazimierza Wielkiego": "https://waszaedukacja.pl/ponadgimnazjalne/xliii-liceum-im-kazimierza-wielkiego-warszawa-207",
  "XLIV Liceum Ogólnokształcące im. Stefana Banacha": "https://waszaedukacja.pl/ponadgimnazjalne/xliv-liceum-im-stefana-banacha-warszawa-206",
  "XLIX Liceum Ogólnokształcące z Odd. Dwujęzycznymi im. Johanna Wolfganga Goethego": "https://waszaedukacja.pl/ponadgimnazjalne/xlix-liceum-z-oddzialami-dwujezycznymi-im-johanna-wolfganga-goethego-warszawa-205",
  "XLV Liceum Ogólnokształcące im. Romualda Traugutta": "https://waszaedukacja.pl/ponadgimnazjalne/xlv-liceum-im-romualda-traugutta-warszawa-204",
  "XLVI Liceum Ogólnokształcące z Oddziałami Dwujęzycznymi im. Stefana Czarnieckiego": "https://waszaedukacja.pl/ponadgimnazjalne/xlvi-liceum-z-oddzialami-dwujezycznymi-im-stefana-czarnieckiego-warszawa-203",
  "XLVII Liceum Ogólnokształcące im. Stanisława Wyspiańskiego": "https://waszaedukacja.pl/ponadgimnazjalne/xlvii-liceum-im-stanislawa-wyspianskiego-warszawa-202",
  "XLVIII Liceum Ogólnokształcące im. Edwarda Dembowskiego": "https://waszaedukacja.pl/ponadgimnazjalne/xlviii-liceum-im-edwarda-dembowskiego-warszawa-201",
  "XV Liceum Ogólnokształcące z Oddziałami Dwujęzycznymi im. Narcyzy Żmichowskiej": "https://waszaedukacja.pl/ponadgimnazjalne/xv-liceum-z-oddzialami-dwujezycznymi-im-narcyzy-zmichowskiej-warszawa-199",
  "XVI Liceum Ogólnokształcące z Oddziałami Dwujęzycznymi im. Stefanii Sempołowskiej": "https://waszaedukacja.pl/ponadgimnazjalne/xvi-liceum-z-oddzialami-dwujezycznymi-im-stefanii-sempolowskiej-warszawa-198",
  "XVII Liceum Ogólnokształcące z Oddziałami Dwujęzycznymi im. Andrzeja Frycza Modrzewskiego": "https://waszaedukacja.pl/ponadgimnazjalne/xvii-liceum-z-oddzialami-dwujezycznymi-im-andrzeja-frycza-modrzewskiego-warszawa-197",
  "XVIII Liceum Ogólnokształcące im. Jana Zamoyskiego": "https://waszaedukacja.pl/ponadgimnazjalne/xviii-liceum-im-jana-zamoyskiego-warszawa-196",
  "XX Liceum Ogólnokształcące im. Bolesława Chrobrego": "https://waszaedukacja.pl/ponadgimnazjalne/xx-liceum-im-boleslawa-chrobrego-warszawa-195",
  "XXI Liceum Ogólnokształcące im. Hugona Kołłątaja": "https://waszaedukacja.pl/ponadgimnazjalne/xxi-liceum-im-hugona-kollataja-warszawa-194",
  "XXII Liceum Ogólnokształcące z Oddziałami Dwujęzycznymi im. Jose Marti": "https://waszaedukacja.pl/ponadgimnazjalne/xxii-liceum-z-oddzialami-dwujezycznymi-im-jose-marti-warszawa-193",
  "XXIII Liceum Ogólnokształcące im. Marii Skłodowskiej-Curie": "https://waszaedukacja.pl/ponadgimnazjalne/xxiii-liceum-im-marii-sklodowskiej-curie-warszawa-192",
  "XXIV Liceum Ogólnokształcące im. Cypriana Kamila Norwida": "https://waszaedukacja.pl/ponadgimnazjalne/xxiv-liceum-im-cypriana-kamila-norwida-warszawa-191",
  "XXV Liceum Ogólnokształcące im. Józefa Wybickiego": "https://waszaedukacja.pl/ponadgimnazjalne/xxv-liceum-im-jozefa-wybickiego-warszawa-190",
  "XXVI Liceum Ogólnokształcące im. Juliana Tuwima": "https://waszaedukacja.pl/ponadgimnazjalne/xxvi-liceum-im-gen-henryka-jankowskiego-warszawa-189",
  "XXVII Liceum Ogólnokształcące im. Tadeusza Czackiego": "https://waszaedukacja.pl/ponadgimnazjalne/xxvii-liceum-im-tadeusza-czackiego-warszawa-187",
  "XXVIII Liceum Ogólnokształcące im. Jana Kochanowskiego": "https://waszaedukacja.pl/ponadgimnazjalne/xxviii-liceum-im-jana-kochanowskiego-warszawa-186",
  "XXX Liceum Ogólnokształcące im. Jana Śniadeckiego": "https://waszaedukacja.pl/ponadgimnazjalne/xxx-liceum-im-jana-sniadeckiego-warszawa-185",
  "XXXII Liceum Ogólnokształcące im. Stefana Grota-Roweckiego": "https://waszaedukacja.pl/ponadgimnazjalne/xxxii-liceum-im-stefana-grota-roweckiego-warszawa-184",
  "XXXIII Liceum Ogólnokształcące Dwujęzyczne im. Mikołaja Kopernika": "https://waszaedukacja.pl/ponadgimnazjalne/xxxiii-liceum-dwujezyczne-im-mikolaja-kopernika-warszawa-183",
  "XXXIV Liceum Ogólnokształcące z Oddziałami Dwujęzycznymi im. Miguela de Cervantesa": "https://waszaedukacja.pl/ponadgimnazjalne/xxxiv-liceum-z-oddzialami-dwujezycznymi-im-miguela-de-cervantesa-warszawa-181",
  "XXXIX Liceum Ogólnokształcące im. Lotnictwa Polskiego": "https://waszaedukacja.pl/ponadgimnazjalne/xxxix-liceum-im-lotnictwa-polskiego-warszawa-180",
  "XXXV Liceum Ogólnokształcące z Oddziałami Dwujęzycznymi im. Bolesława Prusa": "https://waszaedukacja.pl/ponadgimnazjalne/xxxv-liceum-z-oddzialami-dwujezycznymi-im-boleslawa-prusa-warszawa-179",
  "XXXVII Liceum Ogólnokształcące im. Jarosława Dąbrowskiego": "https://waszaedukacja.pl/ponadgimnazjalne/xxxvii-liceum-im-jaroslawa-dabrowskiego-warszawa-178",
  "XXXVIII Liceum Ogólnokształcące im. Stanisława Kostki Potockiego": "https://waszaedukacja.pl/ponadgimnazjalne/xxxviii-liceum-im-st-kostki-potockiego-warszawa-177",
  "Technikum Architektoniczno-Budowlane im. Stanisława Noakowskiego": "https://waszaedukacja.pl/ponadgimnazjalne/technikum-architektoniczno-budowlane-im-stanislawa-noakowskiego-warszawa-345",
  "Technikum Budowlane nr 5 im. prof. Stefana Bryły": "https://waszaedukacja.pl/ponadgimnazjalne/technikum-budowlane-nr-5-im-prof-stefana-bryly-warszawa-347",
  "Technikum Budownictwa i Architektury nr 1 im. prof. Zdzisława Mączeńskiego": "https://waszaedukacja.pl/ponadgimnazjalne/technikum-budownictwa-i-architektury-nr-1-im-prof-zdzislawa-maczenskiego-warszawa-346",
  "Technikum Ekonomiczne nr 1 im. Mikołaja Kopernika": "https://waszaedukacja.pl/ponadgimnazjalne/technikum-ekonomiczne-nr-1-im-mikolaja-kopernika-warszawa-349",
  "Technikum Ekonomiczne nr 5": "https://waszaedukacja.pl/ponadgimnazjalne/technikum-ekonomiczne-nr-5-warszawa-350",
  "Technikum Ekonomiczne nr 8": "https://waszaedukacja.pl/ponadgimnazjalne/technikum-ekonomiczne-nr-8-warszawa-351",
  "Technikum Elektroniczne nr 1": "https://waszaedukacja.pl/ponadgimnazjalne/technikum-elektroniczne-nr-1-warszawa-352",
  "Technikum Elektroniczne nr 3 im. Żołnierzy Armii Krajowej \"Żywiciel\"": "https://waszaedukacja.pl/ponadgimnazjalne/technikum-elektroniczne-nr-3-im-zolnierzy-armii-krajowej-warszawa-353",
  "Technikum Elektryczne nr 2 im. Synów Pułku": "https://waszaedukacja.pl/ponadgimnazjalne/technikum-elektryczne-nr-2-im-synow-pulku-warszawa-354",
  "Technikum Fototechniczne": "https://waszaedukacja.pl/ponadgimnazjalne/technikum-fototechniczne-warszawa-356",
  "Technikum Gastronomiczno-Hotelarskie nr 1": "https://waszaedukacja.pl/ponadgimnazjalne/technikum-gastronomiczno-hotelarskie-nr-1-warszawa-357",
  "Technikum Gastronomiczno-Hotelarskie nr 2 im. prof. Stanisława Bergera": "https://waszaedukacja.pl/ponadgimnazjalne/technikum-gastronomiczno-hotelarskie-nr-2-im-prof-stanislawa-bergera-warszawa-358",
  "Technikum Geologiczno-Geodezyjno-Drogowe im. prof. dr Stanisława Kluźniaka": "https://waszaedukacja.pl/ponadgimnazjalne/technikum-geologiczno-geodezyjno-drogowe-im-prof-dr-stanislawa-kluzniaka-warszawa-359",
  "Technikum Hotelarsko-Turystyczno-Gastronomiczne nr 21": "https://waszaedukacja.pl/ponadgimnazjalne/technikum-hotelarsko-turystyczno-gastronomiczne-nr-21-warszawa-360",
  "Technikum Kinematograficzno-Komputerowe im. Krzysztofa Kieślowskiego": "https://waszaedukacja.pl/ponadgimnazjalne/technikum-kinematograficzno-komputerowe-im-krzysztofa-kieslowskiego-warszawa-18803",
  "Technikum Księgarskie im. Stefana Żeromskiego": "https://waszaedukacja.pl/ponadgimnazjalne/technikum-ksiegarskie-im-stefana-zeromskiego-warszawa-361",
  "Technikum Mechaniczne nr 5 im. Stefana Starzyńskiego": "https://waszaedukacja.pl/ponadgimnazjalne/technikum-mechaniczne-nr-5-im-stefana-starzynskiego-warszawa-362",
  "Technikum Mechaniczne nr 7 im. Jana Kilińskiego": "https://waszaedukacja.pl/ponadgimnazjalne/technikum-mechaniczne-nr-7-im-jana-kilinskiego-warszawa-363",
  "Technikum Mechatroniczne nr 1": "https://waszaedukacja.pl/ponadgimnazjalne/technikum-mechatroniczne-nr-1-warszawa-364",
  "Technikum Odzieżowe i Fryzjerskie im. Marii Bratkowskiej": "https://waszaedukacja.pl/ponadgimnazjalne/technikum-odziezowe-i-fryzjerskie-im-marii-bratkowskiej-warszawa-382",
  "Technikum Ogrodnicze": "https://waszaedukacja.pl/ponadgimnazjalne/technikum-ogrodnicze-warszawa-383",
  "Technikum Poligraficzne": "https://waszaedukacja.pl/ponadgimnazjalne/technikum-poligraficzne-warszawa-384",
  "Technikum Samochodowe nr 1 im. Romana Macieja Pijanowskiego": "https://waszaedukacja.pl/ponadgimnazjalne/technikum-samochodowe-nr-1-im-romana-macieja-pijanowskiego-warszawa-385",
  "Technikum Samochodowe nr 2 im. Mariana Bublewicza": "https://waszaedukacja.pl/ponadgimnazjalne/technikum-samochodowe-nr-2-im-czeslawa-orlowskiego-warszawa-386",
  "Technikum Samochodowe nr 3": "https://waszaedukacja.pl/ponadgimnazjalne/technikum-samochodowe-nr-3-warszawa-387",
  "Technikum Spożywczo-Gastronomiczne im. Jana Pawła II": "https://waszaedukacja.pl/ponadgimnazjalne/technikum-spozywczo-gastronomiczne-im-jana-pawla-ii-warszawa-388",
  "Technikum nr 10 im. Eugeniusza Kwiatkowskiego": "https://waszaedukacja.pl/ponadgimnazjalne/technikum-nr-10-im-eugeniusza-kwiatkowskiego-warszawa-365",
  "Technikum nr 11 im. Piotra Wysockiego": "https://waszaedukacja.pl/ponadgimnazjalne/technikum-nr-11-im-piotra-wysockiego-warszawa-366",
  "Technikum nr 12": "https://waszaedukacja.pl/ponadgimnazjalne/technikum-nr-12-warszawa-367",
  "Technikum nr 2 z Oddziałami Integracyjnymi": "https://waszaedukacja.pl/ponadgimnazjalne/technikum-nr-2-z-oddzialami-integracyjnymi-warszawa-368",
  "Technikum nr 20": "https://waszaedukacja.pl/ponadgimnazjalne/technikum-nr-20-warszawa-369",
  "Technikum nr 23 im. Fryderyka Skarbka": "https://waszaedukacja.pl/ponadgimnazjalne/technikum-nr-23-im-fryderyka-skarbka-warszawa-370",
  "Technikum nr 24": "https://waszaedukacja.pl/ponadgimnazjalne/technikum-nr-24-warszawa-371",
  "Technikum nr 25 im. Stanisława Staszica": "https://waszaedukacja.pl/ponadgimnazjalne/technikum-nr-25-im-stanislawa-staszica-warszawa-372",
  "Technikum nr 26": "https://waszaedukacja.pl/ponadgimnazjalne/technikum-nr-26-warszawa-373",
  "Technikum nr 27 im. prof. Józefa Zawadzkiego": "https://waszaedukacja.pl/ponadgimnazjalne/technikum-nr-27-im-prof-jozefa-zawadzkiego-warszawa-374",
  "Technikum nr 29": "https://waszaedukacja.pl/ponadgimnazjalne/technikum-nr-29-warszawa-375",
  "Technikum nr 3 im. Ludwika Krzywickiego": "https://waszaedukacja.pl/ponadgimnazjalne/technikum-nr-3-im-ludwika-krzywickiego-warszawa-376",
  "Technikum nr 30": "https://waszaedukacja.pl/ponadgimnazjalne/technikum-nr-30-warszawa-377",
  "Technikum nr 6": "https://waszaedukacja.pl/ponadgimnazjalne/technikum-nr-6-warszawa-378",
  "Technikum nr 7": "https://waszaedukacja.pl/ponadgimnazjalne/technikum-nr-7-warszawa-379",
  "Technikum nr 8 im. Jana Karskiego": "https://waszaedukacja.pl/ponadgimnazjalne/technikum-nr-8-im-jana-karskiego-warszawa-380",
  "Technikum nr 9 Lotnicze im. Bohaterów Narwiku": "https://waszaedukacja.pl/ponadgimnazjalne/technikum-nr-9-lotnicze-im-bohaterow-narwiku-warszawa-381",
  "Technikum Łączności im. prof. dr inż. Janusza Groszkowskiego": "https://waszaedukacja.pl/ponadgimnazjalne/technikum-lacznosci-im-prof-dr-inz-janusza-groszkowskiego-warszawa-389",
  "Branżowa Szkoła Fototechniczna I stopnia": "https://waszaedukacja.pl/ponadgimnazjalne/branzowa-szkola-fototechniczna-i-stopnia-warszawa-175",
  "Branżowa Szkoła Gastronomiczna I stopnia": "https://waszaedukacja.pl/ponadgimnazjalne/branzowa-szkola-gastronomiczna-i-stopnia-warszawa-174",
  "Branżowa Szkoła I stopnia Nr 18": "https://waszaedukacja.pl/ponadgimnazjalne/branzowa-szkola-i-stopnia-nr-18-warszawa-166",
  "Branżowa Szkoła I stopnia Nr 61": "https://waszaedukacja.pl/ponadgimnazjalne/branzowa-szkola-i-stopnia-nr-61-warszawa-154",
  "Branżowa Szkoła I stopnia nr 11": "https://waszaedukacja.pl/ponadgimnazjalne/branzowa-szkola-i-stopnia-nr-11-warszawa-168",
  "Branżowa Szkoła I stopnia nr 20 im. prof. Stanisława Bergera": "https://waszaedukacja.pl/ponadgimnazjalne/branzowa-szkola-i-stopnia-nr-20-im-prof-stanislawa-bergera-warszawa-165",
  "Branżowa Szkoła I stopnia nr 31": "https://waszaedukacja.pl/ponadgimnazjalne/branzowa-szkola-i-stopnia-nr-31-warszawa-164",
  "Branżowa Szkoła I stopnia nr 37 im. Jana Karskiego": "https://waszaedukacja.pl/ponadgimnazjalne/branzowa-szkola-i-stopnia-nr-37-im-jana-karskiego-warszawa-163",
  "Branżowa Szkoła I stopnia nr 39": "https://waszaedukacja.pl/ponadgimnazjalne/branzowa-szkola-i-stopnia-nr-39-warszawa-162",
  "Branżowa Szkoła I stopnia nr 4": "https://waszaedukacja.pl/ponadgimnazjalne/zasadnicza-szkola-zawodowa-nr-4-warszawa-161",
  "Branżowa Szkoła I stopnia nr 41": "https://waszaedukacja.pl/ponadgimnazjalne/branzowa-szkola-i-stopnia-nr-41-warszawa-160",
  "Branżowa Szkoła I stopnia nr 6 im. Michała Konarskiego": "https://waszaedukacja.pl/ponadgimnazjalne/branzowa-szkola-i-stopnia-nr-6-im-michala-konarskiego-warszawa-157",
  "Branżowa Szkoła I stopnia nr 66": "https://waszaedukacja.pl/ponadgimnazjalne/branzowa-szkola-i-stopnia-nr-66-warszawa-500",
  "Branżowa Szkoła Rzemiosł Artystycznych I stopnia nr 65": "https://waszaedukacja.pl/ponadgimnazjalne/branzowa-szkola-rzemiosl-artystycznych-i-stopnia-nr-65-warszawa-150",
  "Branżowa Szkoła Samochodowa I stopnia nr 1": "https://waszaedukacja.pl/ponadgimnazjalne/branzowa-szkola-samochodowa-i-stopnia-nr-1-warszawa-171",
  "Branżowa Szkoła Samochodowa I stopnia nr 2": "https://waszaedukacja.pl/ponadgimnazjalne/branzowa-szkola-samochodowa-i-stopnia-nr-2-warszawa-170",
  "Branżowa Szkoła Spożywczo-Gastronomiczna I stopnia im. Jana Pawła II": "https://waszaedukacja.pl/ponadgimnazjalne/branzowa-szkola-spozywczo-gastronomiczna-i-stopnia-im-jana-pawla-ii-warszawa-169",
};
