export const SCHOOL_RATINGS = {
  "CII Liceum Ogólnokształcące z Oddziałami Integracyjnymi im. Księdza Józefa Woźniaka": { rating: 2.82, reviews: 22 },
  "CLIX Liceum Ogólnokształcące im. Króla Jana III Sobieskiego": { rating: 3.63, reviews: 46 },
  "CLV Liceum Ogólnokształcące z Oddziałami Dwujęzycznymi im. Bohaterek Powstania Warszawskiego": { rating: 3.35, reviews: 99 },
  "CLVI Liceum Ogólnokształcące Integracyjne „Przy Łazienkach Królewskich”": { rating: 4.0, reviews: 21 },
  "CLVII Liceum Ogólnokształcące im. Marii Skłodowskiej-Curie": { rating: 2.73, reviews: 49 },
  "CLVIII Liceum Ogólnokształcące z Oddziałami Dwujęzycznymi im. Księżnej Izabeli Czartoryskiej": { rating: 4.0, reviews: 24 },
  "CLX Liceum Ogólnokształcące im. gen. dyw. Stefana Roweckiego „Grota”": { rating: 2.89, reviews: 122 },
  "CLXI Liceum Ogólnokształcące im. Władysława Bartoszewskiego": { rating: 3.64, reviews: 45 },
  "CLXII Liceum Ogólnokształcące im. Szarych Szeregów": { rating: 2.06, reviews: 32 },
  "CLXIII Liceum Ogólnokształcące im. Czesława Niemena w Warszawie": { rating: 3.65, reviews: 20 },
  "CLXIV Liceum Ogólnokształcące Mistrzostwa Sportowego": { rating: 3.0, reviews: 7 },
  "CLXV Liceum Ogólnokształcące": { rating: 3.59, reviews: 137 },
  "CLXVI Liceum Ogólnokształcące z Oddziałami Sportowymi": { rating: 2.92, reviews: 12 },
  "CV Liceum Ogólnokształcące im. Zbigniewa Herberta": { rating: 3.07, reviews: 69 },
  "CX Liceum Ogólnokształcące im. Roberta Schumana": { rating: 3.55, reviews: 20 },
  "CXI Liceum Ogólnokształcące z Oddziałami Integracyjnymi im. Stefana Kisielewskiego": { rating: 4.2, reviews: 5 },
  "CXIV Liceum Ogólnokształcące im. Jana Kilińskiego": { rating: 3.72, reviews: 32 },
  "CXIX Liceum Ogólnokształcące im. Jacka Kuronia": { rating: 3.03, reviews: 125 },
  "CXXII Liceum Ogólnokształcące im. Ignacego Domeyki": { rating: 3.47, reviews: 79 },
  "CXXV Liceum Ogólnokształcące im. Waldemara Milewicza": { rating: 2.49, reviews: 51 },
  "CXXXVII Liceum Ogólnokształcące z Oddziałami Dwujęzycznymi im. Roberta Schumana": { rating: 3.87, reviews: 67 },
  "I Liceum Ogólnokształcące z Oddziałami Integracyjnymi im. Bolesława Limanowskiego": { rating: 3.08, reviews: 477 },
  "II Liceum Ogólnokształcące z Oddziałami Dwujęzycznymi im. Stefana Batorego": { rating: 3.68, reviews: 90 },
  "III Liceum Ogólnokształcące im. gen. Józefa Sowińskiego": { rating: 3.49, reviews: 140 },
  "IV Liceum Ogólnokształcące im. Adama Mickiewicza": { rating: 3.59, reviews: 76 },
  "IX Liceum Ogólnokształcące im. Klementyny Hoffmanowej": { rating: 2.69, reviews: 141 },
  "L Liceum Ogólnokształcące z Oddziałami Integracyjnymi im. Ruy Barbosy": { rating: 2.25, reviews: 158 },
  "LI Liceum Ogólnokształcące im. Tadeusza Kościuszki": { rating: 3.04, reviews: 28 },
  "LII Liceum Ogólnokształcące im. Władysława Stanisława Reymonta": { rating: 3.55, reviews: 51 },
  "LVI Liceum Ogólnokształcące im. Rotmistrza Witolda Pileckiego": { rating: 3.28, reviews: 36 },
  "LVIII Liceum Ogólnokształcące im. Krzysztofa Kamila Baczyńskiego": { rating: 1.65, reviews: 263 },
  "LX Liceum Ogólnokształcące im. Wojciecha Górskiego": { rating: 3.95, reviews: 41 },
  "LXII Liceum Ogólnokształcące Mistrzostwa Sportowego im. Generała Broni Władysława Andersa": { rating: 3.75, reviews: 12 },
  "LXIII Liceum Ogólnokształcące im. Lajosa Kossutha": { rating: 2.04, reviews: 191 },
  "LXIX Liceum Ogólnokształcące z Oddziałami Integracyjnymi im. Bohaterów Powstania Warszawskiego 1944": { rating: 2.48, reviews: 60 },
  "LXV Liceum Ogólnokształcące z Oddziałami Integracyjnymi im. gen. Józefa Bema": { rating: 2.94, reviews: 71 },
  "LXVII Liceum Ogólnokształcące im. Jana Nowaka-Jeziorańskiego": { rating: 3.33, reviews: 135 },
  "LXVIII Liceum Ogólnokształcące im. Tytusa Chałubińskiego": { rating: 2.41, reviews: 124 },
  "LXX Liceum Ogólnokształcące im. Aleksandra Kamińskiego": { rating: 3.12, reviews: 85 },
  "LXXII Liceum Ogólnokształcące im. gen. Jakuba Jasińskiego": { rating: 3.28, reviews: 40 },
  "LXXV Liceum Ogólnokształcące im. Jana III Sobieskiego": { rating: 2.84, reviews: 110 },
  "LXXVI Liceum Ogólnokształcące im. Marszałka Józefa Piłsudskiego": { rating: 3.28, reviews: 71 },
  "LXXVIII Liceum Ogólnokształcące im. Marii Pawlikowskiej-Jasnorzewskiej": { rating: 3.07, reviews: 99 },
  "LXXX Liceum Ogólnokształcące im. Leopolda Staffa": { rating: 3.65, reviews: 26 },
  "LXXXI Liceum Ogólnokształcące im. Aleksandra Fredry": { rating: 3.64, reviews: 129 },
  "LXXXIII Liceum Ogólnokształcące im. Emiliana Konopczyńskiego": { rating: 3.48, reviews: 145 },
  "LXXXIV Liceum Ogólnokształcące im. Bohaterów Narwiku": { rating: 3.86, reviews: 7 },
  "LXXXVII Liceum Ogólnokształcące im. gen. Leopolda Okulickiego": { rating: 3.5, reviews: 8 },
  "LXXXVIII Liceum Ogólnokształcące im. Michała Konarskiego": { rating: 2.71, reviews: 41 },
  "V Liceum Ogólnokształcące im. Księcia Józefa Poniatowskiego": { rating: 4.06, reviews: 103 },
  "VI Liceum Ogólnokształcące im. Tadeusza Reytana": { rating: 3.16, reviews: 159 },
  "VII Liceum Ogólnokształcące im. Juliusza Słowackiego": { rating: 3.49, reviews: 195 },
  "VIII Liceum Ogólnokształcące im. Władysława IV": { rating: 3.92, reviews: 97 },
  "X Liceum Ogólnokształcące im. Królowej Jadwigi": { rating: 3.46, reviews: 57 },
  "XCII Liceum Ogólnokształcące z Oddziałami Integracyjnymi": { rating: 3.32, reviews: 19 },
  "XCIV Liceum Ogólnokształcące im. gen. Stanisława Maczka": { rating: 3.53, reviews: 77 },
  "XCIX Liceum Ogólnokształcące z Oddziałami Dwujęzycznymi im. Zbigniewa Herberta": { rating: 3.36, reviews: 47 },
  "XCVI Liceum Ogólnokształcące im. Agnieszki Osieckiej": { rating: 2.77, reviews: 13 },
  "XCVII Liceum Ogólnokształcące im. Olimpijczyków Polskich": { rating: 2.67, reviews: 9 },
  "XI Liceum Ogólnokształcące im. Mikołaja Reja": { rating: 3.06, reviews: 143 },
  "XII Liceum Ogólnokształcące im. Henryka Sienkiewicza": { rating: 3.68, reviews: 94 },
  "XIII Liceum Ogólnokształcące z Oddziałami Dwujęzycznymi im. płk. Leopolda Lisa-Kuli": { rating: 2.81, reviews: 156 },
  "XIV Liceum Ogólnokształcące im. Stanisława Staszica": { rating: 3.17, reviews: 132 },
  "XIX Liceum Ogólnokształcące im. Powstańców Warszawy": { rating: 3.49, reviews: 67 },
  "XL Liceum Ogólnokształcące z Oddziałami Dwujęzycznymi im. Stefana Żeromskiego": { rating: 3.7, reviews: 138 },
  "XLI Liceum Ogólnokształcące im. Joachima Lelewela": { rating: 3.45, reviews: 80 },
  "XLII Liceum Ogólnokształcące im. Marii Konopnickiej": { rating: 2.95, reviews: 74 },
  "XLIII Liceum Ogólnokształcące im. Kazimierza Wielkiego": { rating: 3.84, reviews: 62 },
  "XLIV Liceum Ogólnokształcące im. Stefana Banacha": { rating: 3.26, reviews: 70 },
  "XLIX Liceum Ogólnokształcące z Odd. Dwujęzycznymi im. Johanna Wolfganga Goethego": { rating: 3.68, reviews: 123 },
  "XLV Liceum Ogólnokształcące im. Romualda Traugutta": { rating: 3.08, reviews: 187 },
  "XLVI Liceum Ogólnokształcące z Oddziałami Dwujęzycznymi im. Stefana Czarnieckiego": { rating: 3.38, reviews: 78 },
  "XLVII Liceum Ogólnokształcące im. Stanisława Wyspiańskiego": { rating: 2.7, reviews: 74 },
  "XLVIII Liceum Ogólnokształcące im. Edwarda Dembowskiego": { rating: 3.08, reviews: 164 },
  "XV Liceum Ogólnokształcące z Oddziałami Dwujęzycznymi im. Narcyzy Żmichowskiej": { rating: 3.12, reviews: 99 },
  "XVI Liceum Ogólnokształcące z Oddziałami Dwujęzycznymi im. Stefanii Sempołowskiej": { rating: 3.73, reviews: 55 },
  "XVII Liceum Ogólnokształcące z Oddziałami Dwujęzycznymi im. Andrzeja Frycza Modrzewskiego": { rating: 3.49, reviews: 61 },
  "XVIII Liceum Ogólnokształcące im. Jana Zamoyskiego": { rating: 3.46, reviews: 160 },
  "XX Liceum Ogólnokształcące im. Bolesława Chrobrego": { rating: 2.6, reviews: 5 },
  "XXI Liceum Ogólnokształcące im. Hugona Kołłątaja": { rating: 1.99, reviews: 422 },
  "XXII Liceum Ogólnokształcące z Oddziałami Dwujęzycznymi im. Jose Marti": { rating: 3.68, reviews: 152 },
  "XXIII Liceum Ogólnokształcące im. Marii Skłodowskiej-Curie": { rating: 2.98, reviews: 52 },
  "XXIV Liceum Ogólnokształcące im. Cypriana Kamila Norwida": { rating: 2.19, reviews: 208 },
  "XXV Liceum Ogólnokształcące im. Józefa Wybickiego": { rating: 3.27, reviews: 48 },
  "XXVI Liceum Ogólnokształcące im. Juliana Tuwima": { rating: 3.0, reviews: 9 },
  "XXVII Liceum Ogólnokształcące im. Tadeusza Czackiego": { rating: 3.63, reviews: 79 },
  "XXVIII Liceum Ogólnokształcące im. Jana Kochanowskiego": { rating: 3.04, reviews: 103 },
  "XXX Liceum Ogólnokształcące im. Jana Śniadeckiego": { rating: 3.45, reviews: 171 },
  "XXXII Liceum Ogólnokształcące im. Stefana Grota-Roweckiego": { rating: 3.0, reviews: 8 },
  "XXXIII Liceum Ogólnokształcące Dwujęzyczne im. Mikołaja Kopernika": { rating: 3.11, reviews: 88 },
  "XXXIV Liceum Ogólnokształcące z Oddziałami Dwujęzycznymi im. Miguela de Cervantesa": { rating: 3.54, reviews: 39 },
  "XXXIX Liceum Ogólnokształcące im. Lotnictwa Polskiego": { rating: 3.84, reviews: 63 },
  "XXXV Liceum Ogólnokształcące z Oddziałami Dwujęzycznymi im. Bolesława Prusa": { rating: 3.6, reviews: 67 },
  "XXXVII Liceum Ogólnokształcące im. Jarosława Dąbrowskiego": { rating: 3.36, reviews: 95 },
  "XXXVIII Liceum Ogólnokształcące im. Stanisława Kostki Potockiego": { rating: 1.8, reviews: 61 },
  "Technikum Architektoniczno-Budowlane im. Stanisława Noakowskiego": { rating: 2.65, reviews: 43 },
  "Technikum Budowlane nr 5 im. prof. Stefana Bryły": { rating: 2.47, reviews: 17 },
  "Technikum Budownictwa i Architektury nr 1 im. prof. Zdzisława Mączeńskiego": { rating: 3.08, reviews: 12 },
  "Technikum Ekonomiczne nr 1 im. Mikołaja Kopernika": { rating: 3.46, reviews: 50 },
  "Technikum Ekonomiczne nr 5": { rating: 2.14, reviews: 7 },
  "Technikum Ekonomiczne nr 8": { rating: 2.86, reviews: 21 },
  "Technikum Elektroniczne nr 1": { rating: 3.07, reviews: 30 },
  "Technikum Elektroniczne nr 3 im. Żołnierzy Armii Krajowej \"Żywiciel\"": { rating: 2.32, reviews: 37 },
  "Technikum Elektryczne nr 2 im. Synów Pułku": { rating: 3.63, reviews: 65 },
  "Technikum Fototechniczne": { rating: 4.5, reviews: 30 },
  "Technikum Gastronomiczno-Hotelarskie nr 1": { rating: 3.0, reviews: 18 },
  "Technikum Gastronomiczno-Hotelarskie nr 2 im. prof. Stanisława Bergera": { rating: 3.43, reviews: 21 },
  "Technikum Geologiczno-Geodezyjno-Drogowe im. prof. dr Stanisława Kluźniaka": { rating: 1.75, reviews: 32 },
  "Technikum Hotelarsko-Turystyczno-Gastronomiczne nr 21": { rating: 3.4, reviews: 10 },
  "Technikum Kinematograficzno-Komputerowe im. Krzysztofa Kieślowskiego": { rating: 3.36, reviews: 11 },
  "Technikum Księgarskie im. Stefana Żeromskiego": { rating: 2.0, reviews: 22 },
  "Technikum Mechaniczne nr 5 im. Stefana Starzyńskiego": { rating: 2.9, reviews: 21 },
  "Technikum Mechaniczne nr 7 im. Jana Kilińskiego": { rating: 4.2, reviews: 5 },
  "Technikum Mechatroniczne nr 1": { rating: 2.75, reviews: 111 },
  "Technikum Odzieżowe i Fryzjerskie im. Marii Bratkowskiej": { rating: 2.36, reviews: 11 },
  "Technikum Ogrodnicze": { rating: 3.78, reviews: 32 },
  "Technikum Poligraficzne": { rating: 2.26, reviews: 23 },
  "Technikum Samochodowe nr 1 im. Romana Macieja Pijanowskiego": { rating: 4.3, reviews: 20 },
  "Technikum Samochodowe nr 2 im. Mariana Bublewicza": { rating: 2.62, reviews: 37 },
  "Technikum Samochodowe nr 3": { rating: 3.15, reviews: 13 },
  "Technikum Spożywczo-Gastronomiczne im. Jana Pawła II": { rating: 3.86, reviews: 14 },
  "Technikum nr 10 im. Eugeniusza Kwiatkowskiego": { rating: 3.44, reviews: 25 },
  "Technikum nr 11 im. Piotra Wysockiego": { rating: 3.08, reviews: 49 },
  "Technikum nr 12": { rating: 3.5, reviews: 8 },
  "Technikum nr 2 z Oddziałami Integracyjnymi": { rating: 4.0, reviews: 3 },
  "Technikum nr 20": { rating: 3.13, reviews: 15 },
  "Technikum nr 23 im. Fryderyka Skarbka": { rating: 4.76, reviews: 20 },
  "Technikum nr 24": { rating: 2.63, reviews: 60 },
  "Technikum nr 25 im. Stanisława Staszica": { rating: 2.39, reviews: 46 },
  "Technikum nr 26": { rating: 2.33, reviews: 12 },
  "Technikum nr 27 im. prof. Józefa Zawadzkiego": { rating: 3.13, reviews: 15 },
  "Technikum nr 29": { rating: 2.39, reviews: 18 },
  "Technikum nr 3 im. Ludwika Krzywickiego": { rating: 2.17, reviews: 24 },
  "Technikum nr 30": { rating: 3.13, reviews: 8 },
  "Technikum nr 6": { rating: 3.0, reviews: 2 },
  "Technikum nr 7": { rating: 2.74, reviews: 43 },
  "Technikum nr 8 im. Jana Karskiego": { rating: 3.13, reviews: 24 },
  "Technikum nr 9 Lotnicze im. Bohaterów Narwiku": { rating: 2.54, reviews: 74 },
  "Technikum Łączności im. prof. dr inż. Janusza Groszkowskiego": { rating: 3.29, reviews: 78 },
  "Branżowa Szkoła Fototechniczna I stopnia": { rating: 1.37, reviews: 15 },
  "Branżowa Szkoła Gastronomiczna I stopnia": { rating: 5.0, reviews: 1 },
  "Branżowa Szkoła I stopnia Nr 18": { rating: 3.71, reviews: 65 },
  "Branżowa Szkoła I stopnia Nr 61": { rating: 2.97, reviews: 9 },
  "Branżowa Szkoła I stopnia nr 11": { rating: 3.0, reviews: 2 },
  "Branżowa Szkoła I stopnia nr 20 im. prof. Stanisława Bergera": { rating: 2.58, reviews: 108 },
  "Branżowa Szkoła I stopnia nr 31": { rating: 3.5, reviews: 4 },
  "Branżowa Szkoła I stopnia nr 37 im. Jana Karskiego": { rating: 1.83, reviews: 43 },
  "Branżowa Szkoła I stopnia nr 39": { rating: 3.8, reviews: 32 },
  "Branżowa Szkoła I stopnia nr 4": { rating: 4.69, reviews: 47 },
  "Branżowa Szkoła I stopnia nr 41": { rating: 4.38, reviews: 8 },
  "Branżowa Szkoła I stopnia nr 6 im. Michała Konarskiego": { rating: 2.0, reviews: 2 },
  "Branżowa Szkoła I stopnia nr 66": { rating: 1.42, reviews: 38 },
  "Branżowa Szkoła Rzemiosł Artystycznych I stopnia nr 65": { rating: 4.88, reviews: 42 },
  "Branżowa Szkoła Samochodowa I stopnia nr 1": { rating: 3.0, reviews: 2 },
  "Branżowa Szkoła Samochodowa I stopnia nr 2": { rating: 2.06, reviews: 111 },
  "Branżowa Szkoła Spożywczo-Gastronomiczna I stopnia im. Jana Pawła II": { rating: 3.0, reviews: 1 },
};
